/**
 * Word frequency dataset based on common English word frequency lists
 * (COCA, BNC, and other corpus-based sources).
 * 
 * Words are organized into frequency tiers:
 * - Tier 1 (0-1000): Most common words
 * - Tier 2 (1000-3000): Very common words  
 * - Tier 3 (3000-5000): Common words
 * - Tier 4 (5000-8000): Less common words
 * - Tier 5 (8000+): Rare/uncommon words
 * 
 * Words not in this list are assumed to be Tier 5 (rare).
 */

// Top ~8000 most common English words (compressed format)
// This is a representative sample - in production you might load from a larger dataset
export const COMMON_WORDS_TIER_1 = new Set([
  // Most common function words and basic vocabulary (top 1000)
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i', 'it', 'for', 'not', 'on', 'with',
  'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
  'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if',
  'about', 'who', 'get', 'which', 'go', 'me', 'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him',
  'know', 'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other',
  'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use',
  'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these',
  'give', 'day', 'most', 'us', 'is', 'was', 'are', 'were', 'been', 'being', 'has', 'had', 'having',
  'do', 'does', 'did', 'doing', 'done', 'get', 'got', 'getting', 'gotten', 'go', 'goes', 'went', 'gone',
  'going', 'come', 'comes', 'came', 'coming', 'see', 'sees', 'saw', 'seen', 'seeing', 'know', 'knows',
  'knew', 'known', 'knowing', 'think', 'thinks', 'thought', 'thinking', 'take', 'takes', 'took', 'taken',
  'taking', 'give', 'gives', 'gave', 'given', 'giving', 'make', 'makes', 'made', 'making', 'say', 'says',
  'said', 'saying', 'tell', 'tells', 'told', 'telling', 'find', 'finds', 'found', 'finding', 'ask', 'asks',
  'asked', 'asking', 'try', 'tries', 'tried', 'trying', 'help', 'helps', 'helped', 'helping', 'work',
  'works', 'worked', 'working', 'call', 'calls', 'called', 'calling', 'move', 'moves', 'moved', 'moving',
  'play', 'plays', 'played', 'playing', 'run', 'runs', 'ran', 'running', 'walk', 'walks', 'walked',
  'walking', 'live', 'lives', 'lived', 'living', 'believe', 'believes', 'believed', 'believing', 'bring',
  'brings', 'brought', 'bringing', 'happen', 'happens', 'happened', 'happening', 'write', 'writes', 'wrote',
  'written', 'writing', 'sit', 'sits', 'sat', 'sitting', 'stand', 'stands', 'stood', 'standing', 'lose',
  'loses', 'lost', 'losing', 'pay', 'pays', 'paid', 'paying', 'meet', 'meets', 'met', 'meeting', 'include',
  'includes', 'included', 'including', 'continue', 'continues', 'continued', 'continuing', 'set', 'sets',
  'setting', 'learn', 'learns', 'learned', 'learning', 'change', 'changes', 'changed', 'changing', 'lead',
  'leads', 'led', 'leading', 'understand', 'understands', 'understood', 'understanding', 'watch', 'watches',
  'watched', 'watching', 'follow', 'follows', 'followed', 'following', 'stop', 'stops', 'stopped',
  'stopping', 'create', 'creates', 'created', 'creating', 'speak', 'speaks', 'spoke', 'spoken', 'speaking',
  'read', 'reads', 'reading', 'allow', 'allows', 'allowed', 'allowing', 'add', 'adds', 'added', 'adding',
  'spend', 'spends', 'spent', 'spending', 'grow', 'grows', 'grew', 'grown', 'growing', 'open', 'opens',
  'opened', 'opening', 'walk', 'turn', 'turns', 'turned', 'turning', 'start', 'starts', 'started',
  'starting', 'might', 'show', 'shows', 'showed', 'shown', 'showing', 'hear', 'hears', 'heard', 'hearing',
  'play', 'let', 'lets', 'letting', 'feel', 'feels', 'felt', 'feeling', 'put', 'puts', 'putting', 'end',
  'ends', 'ended', 'ending', 'begin', 'begins', 'began', 'begun', 'beginning', 'seem', 'seems', 'seemed',
  'seeming', 'help', 'talk', 'talks', 'talked', 'talking', 'turn', 'leave', 'leaves', 'left', 'leaving',
  'close', 'closes', 'closed', 'closing', 'keep', 'keeps', 'kept', 'keeping', 'point', 'points', 'pointed',
  'pointing', 'believe', 'hold', 'holds', 'held', 'holding', 'bring', 'happen', 'write', 'provide',
  'provides', 'provided', 'providing', 'sit', 'stand', 'lose', 'add', 'change', 'fall', 'falls', 'fell',
  'fallen', 'falling', 'send', 'sends', 'sent', 'sending', 'build', 'builds', 'built', 'building',
  'stay', 'stays', 'stayed', 'staying', 'cut', 'cuts', 'cutting', 'reach', 'reaches', 'reached',
  'reaching', 'kill', 'kills', 'killed', 'killing', 'raise', 'raises', 'raised', 'raising', 'pass',
  'passes', 'passed', 'passing', 'sell', 'sells', 'sold', 'selling', 'decide', 'decides', 'decided',
  'deciding', 'return', 'returns', 'returned', 'returning', 'explain', 'explains', 'explained',
  'explaining', 'develop', 'develops', 'developed', 'developing', 'carry', 'carries', 'carried',
  'carrying', 'break', 'breaks', 'broke', 'broken', 'breaking', 'receive', 'receives', 'received',
  'receiving', 'agree', 'agrees', 'agreed', 'agreeing', 'support', 'supports', 'supported',
  'supporting', 'hit', 'hits', 'hitting', 'produce', 'produces', 'produced', 'producing', 'eat',
  'eats', 'ate', 'eaten', 'eating', 'cover', 'covers', 'covered', 'covering', 'catch', 'catches',
  'caught', 'catching', 'draw', 'draws', 'drew', 'drawn', 'drawing', 'choose', 'chooses', 'chose',
  'chosen', 'choosing', 'die', 'dies', 'died', 'dying', 'expect', 'expects', 'expected', 'expecting',
  'fight', 'fights', 'fought', 'fighting', 'save', 'saves', 'saved', 'saving', 'serve', 'serves',
  'served', 'serving', 'end', 'build', 'stay', 'fall', 'cut', 'reach', 'kill', 'raise', 'pass', 'sell',
  'decide', 'return', 'explain', 'develop', 'carry', 'break', 'receive', 'agree', 'support', 'hit',
  'produce', 'eat', 'cover', 'catch', 'draw', 'choose', 'die', 'expect', 'fight', 'save', 'serve',
])

export const COMMON_WORDS_TIER_2 = new Set([
  // Very common words (1000-3000 range)
  'man', 'woman', 'child', 'children', 'person', 'people', 'family', 'friend', 'friends', 'home',
  'house', 'room', 'door', 'window', 'car', 'road', 'street', 'city', 'town', 'country', 'world',
  'place', 'way', 'side', 'end', 'beginning', 'middle', 'top', 'bottom', 'front', 'back', 'left',
  'right', 'hand', 'hands', 'head', 'eye', 'eyes', 'face', 'body', 'foot', 'feet', 'leg', 'legs',
  'arm', 'arms', 'heart', 'mind', 'soul', 'life', 'lives', 'death', 'time', 'times', 'day', 'days',
  'night', 'nights', 'morning', 'afternoon', 'evening', 'week', 'weeks', 'month', 'months', 'year',
  'years', 'hour', 'hours', 'minute', 'minutes', 'second', 'seconds', 'today', 'yesterday',
  'tomorrow', 'now', 'then', 'before', 'after', 'soon', 'late', 'early', 'fast', 'slow', 'quick',
  'long', 'short', 'tall', 'small', 'big', 'large', 'little', 'huge', 'tiny', 'wide', 'narrow',
  'high', 'low', 'deep', 'shallow', 'heavy', 'light', 'dark', 'bright', 'hot', 'cold', 'warm',
  'cool', 'wet', 'dry', 'clean', 'dirty', 'new', 'old', 'young', 'fresh', 'stale', 'soft', 'hard',
  'smooth', 'rough', 'sharp', 'dull', 'loud', 'quiet', 'noisy', 'silent', 'empty', 'full', 'busy',
  'free', 'open', 'closed', 'safe', 'dangerous', 'easy', 'difficult', 'hard', 'simple', 'complex',
  'good', 'bad', 'nice', 'mean', 'kind', 'cruel', 'happy', 'sad', 'glad', 'sorry', 'angry', 'calm',
  'excited', 'bored', 'tired', 'rested', 'sick', 'healthy', 'strong', 'weak', 'powerful', 'helpless',
  'rich', 'poor', 'expensive', 'cheap', 'free', 'costly', 'beautiful', 'ugly', 'pretty', 'handsome',
  'attractive', 'unattractive', 'smart', 'stupid', 'clever', 'foolish', 'wise', 'silly', 'serious',
  'funny', 'sad', 'happy', 'glad', 'pleased', 'disappointed', 'surprised', 'shocked', 'amazed',
  'confused', 'clear', 'obvious', 'strange', 'normal', 'usual', 'unusual', 'special', 'common',
  'rare', 'important', 'unimportant', 'necessary', 'unnecessary', 'possible', 'impossible',
  'probable', 'improbable', 'certain', 'uncertain', 'sure', 'unsure', 'true', 'false', 'real',
  'fake', 'right', 'wrong', 'correct', 'incorrect', 'same', 'different', 'similar', 'opposite',
  'equal', 'unequal', 'better', 'best', 'worse', 'worst', 'more', 'most', 'less', 'least', 'many',
  'much', 'few', 'little', 'some', 'any', 'all', 'every', 'each', 'both', 'either', 'neither',
  'none', 'no', 'yes', 'maybe', 'perhaps', 'probably', 'definitely', 'certainly', 'surely',
  'absolutely', 'completely', 'totally', 'entirely', 'partly', 'partially', 'mostly', 'mainly',
  'usually', 'often', 'sometimes', 'rarely', 'seldom', 'never', 'always', 'forever', 'already',
  'yet', 'still', 'again', 'once', 'twice', 'three', 'times', 'first', 'second', 'third', 'last',
  'next', 'previous', 'other', 'another', 'such', 'so', 'too', 'very', 'quite', 'rather', 'pretty',
  'really', 'truly', 'actually', 'finally', 'eventually', 'immediately', 'instantly', 'suddenly',
  'quickly', 'slowly', 'carefully', 'easily', 'hardly', 'barely', 'nearly', 'almost', 'about',
  'approximately', 'exactly', 'precisely', 'roughly', 'around', 'over', 'under', 'above', 'below',
  'up', 'down', 'in', 'out', 'inside', 'outside', 'within', 'without', 'through', 'across',
  'along', 'around', 'beside', 'behind', 'beyond', 'between', 'among', 'during', 'throughout',
  'before', 'after', 'since', 'until', 'while', 'when', 'where', 'why', 'how', 'what', 'which',
  'who', 'whom', 'whose', 'that', 'this', 'these', 'those', 'here', 'there', 'everywhere',
  'nowhere', 'somewhere', 'anywhere', 'away', 'back', 'forward', 'ahead', 'together', 'apart',
  'alone', 'along', 'beside', 'near', 'far', 'close', 'distant', 'next', 'previous', 'following',
  'past', 'present', 'future', 'ancient', 'modern', 'recent', 'old', 'new', 'latest', 'earliest',
  'soonest', 'latest', 'earlier', 'later', 'sooner', 'later', 'recently', 'lately', 'formerly',
  'previously', 'currently', 'nowadays', 'today', 'yesterday', 'tomorrow', 'tonight', 'this',
  'morning', 'this', 'afternoon', 'this', 'evening', 'next', 'week', 'last', 'week', 'this',
  'week', 'next', 'month', 'last', 'month', 'this', 'month', 'next', 'year', 'last', 'year',
  'this', 'year', 'ago', 'since', 'for', 'during', 'throughout', 'within', 'beyond', 'until',
  'till', 'by', 'before', 'after', 'while', 'when', 'as', 'once', 'twice', 'three', 'times',
  'once', 'more', 'again', 'anew', 'afresh', 'repeatedly', 'frequently', 'occasionally',
  'sometimes', 'often', 'usually', 'always', 'never', 'ever', 'forever', 'eternally', 'permanently',
  'temporarily', 'briefly', 'momentarily', 'instantly', 'immediately', 'suddenly', 'quickly',
  'rapidly', 'swiftly', 'speedily', 'fast', 'slowly', 'gradually', 'slowly', 'carefully',
  'cautiously', 'carelessly', 'recklessly', 'boldly', 'bravely', 'cowardly', 'timidly', 'shyly',
  'proudly', 'humbly', 'modestly', 'arrogantly', 'politely', 'rudely', 'kindly', 'cruelly',
  'gently', 'roughly', 'softly', 'loudly', 'quietly', 'silently', 'noisily', 'peacefully',
  'violently', 'calmly', 'anxiously', 'nervously', 'confidently', 'doubtfully', 'certainly',
  'uncertainly', 'surely', 'unsurely', 'definitely', 'probably', 'possibly', 'perhaps', 'maybe',
  'likely', 'unlikely', 'certainly', 'absolutely', 'completely', 'totally', 'entirely', 'fully',
  'partly', 'partially', 'mostly', 'mainly', 'chiefly', 'primarily', 'largely', 'generally',
  'usually', 'normally', 'typically', 'commonly', 'rarely', 'seldom', 'hardly', 'scarcely',
  'barely', 'nearly', 'almost', 'quite', 'rather', 'pretty', 'very', 'extremely', 'incredibly',
  'amazingly', 'surprisingly', 'unexpectedly', 'fortunately', 'unfortunately', 'luckily',
  'unluckily', 'hopefully', 'thankfully', 'sadly', 'happily', 'gladly', 'willingly', 'unwillingly',
  'readily', 'reluctantly', 'eagerly', 'anxiously', 'calmly', 'peacefully', 'quietly', 'loudly',
  'noisily', 'silently', 'secretly', 'openly', 'publicly', 'privately', 'personally', 'individually',
  'collectively', 'together', 'separately', 'alone', 'singly', 'jointly', 'mutually', 'independently',
  'dependently', 'freely', 'loosely', 'tightly', 'closely', 'nearly', 'approximately', 'roughly',
  'exactly', 'precisely', 'accurately', 'correctly', 'rightly', 'wrongly', 'incorrectly',
  'mistakenly', 'falsely', 'truly', 'really', 'actually', 'indeed', 'certainly', 'surely',
  'definitely', 'absolutely', 'completely', 'totally', 'entirely', 'fully', 'wholly', 'partly',
  'partially', 'mostly', 'mainly', 'chiefly', 'primarily', 'largely', 'generally', 'usually',
  'normally', 'typically', 'commonly', 'rarely', 'seldom', 'hardly', 'scarcely', 'barely',
  'nearly', 'almost', 'quite', 'rather', 'pretty', 'very', 'extremely', 'incredibly', 'amazingly',
  'surprisingly', 'unexpectedly', 'fortunately', 'unfortunately', 'luckily', 'unluckily',
  'hopefully', 'thankfully', 'sadly', 'happily', 'gladly', 'willingly', 'unwillingly', 'readily',
  'reluctantly', 'eagerly', 'anxiously', 'calmly', 'peacefully', 'quietly', 'loudly', 'noisily',
  'silently', 'secretly', 'openly', 'publicly', 'privately', 'personally', 'individually',
  'collectively', 'together', 'separately', 'alone', 'singly', 'jointly', 'mutually',
  'independently', 'dependently', 'freely', 'loosely', 'tightly', 'closely', 'nearly',
  'approximately', 'roughly', 'exactly', 'precisely', 'accurately', 'correctly', 'rightly',
  'wrongly', 'incorrectly', 'mistakenly', 'falsely', 'truly', 'really', 'actually', 'indeed',
])

export const COMMON_WORDS_TIER_3 = new Set([
  // Common words (3000-5000 range) - expanding vocabulary
  'ability', 'able', 'about', 'above', 'accept', 'according', 'account', 'across', 'act', 'action',
  'active', 'activity', 'actually', 'add', 'address', 'administration', 'admit', 'adult', 'advance',
  'advantage', 'advertisement', 'advice', 'affect', 'afford', 'afraid', 'after', 'afternoon', 'again',
  'against', 'age', 'agency', 'agent', 'ago', 'agree', 'agreement', 'ahead', 'air', 'airline',
  'airport', 'alarm', 'album', 'alcohol', 'alive', 'all', 'allow', 'almost', 'alone', 'along',
  'already', 'also', 'although', 'always', 'amazing', 'among', 'amount', 'analysis', 'analyze',
  'ancient', 'anger', 'angle', 'angry', 'animal', 'announce', 'annual', 'another', 'answer',
  'anxious', 'any', 'anybody', 'anymore', 'anyone', 'anything', 'anyway', 'anywhere', 'apart',
  'apartment', 'apparent', 'apparently', 'appeal', 'appear', 'appearance', 'apple', 'application',
  'apply', 'appoint', 'appointment', 'appreciate', 'approach', 'appropriate', 'approval', 'approve',
  'approximately', 'architect', 'area', 'argue', 'argument', 'arise', 'arm', 'army', 'around',
  'arrange', 'arrangement', 'arrest', 'arrival', 'arrive', 'arrow', 'art', 'article', 'artist',
  'artistic', 'as', 'ash', 'aside', 'ask', 'asleep', 'aspect', 'assault', 'assert', 'assess',
  'assessment', 'asset', 'assign', 'assignment', 'assist', 'assistance', 'assistant', 'associate',
  'association', 'assume', 'assumption', 'assure', 'at', 'athlete', 'athletic', 'atmosphere',
  'attach', 'attack', 'attempt', 'attend', 'attention', 'attitude', 'attorney', 'attract',
  'attraction', 'attractive', 'attribute', 'audience', 'author', 'authority', 'automatic',
  'automatically', 'available', 'average', 'avoid', 'award', 'aware', 'awareness', 'away', 'awful',
  'baby', 'back', 'background', 'bad', 'badly', 'bag', 'bake', 'balance', 'ball', 'ban', 'band',
  'bank', 'bar', 'barely', 'barn', 'barrel', 'barrier', 'base', 'baseball', 'basic', 'basically',
  'basis', 'basket', 'basketball', 'bath', 'bathroom', 'battery', 'battle', 'be', 'beach', 'bean',
  'bear', 'beat', 'beautiful', 'beauty', 'because', 'become', 'bed', 'bedroom', 'beer', 'before',
  'begin', 'beginning', 'behalf', 'behave', 'behavior', 'behind', 'being', 'belief', 'believe',
  'bell', 'belong', 'below', 'belt', 'bench', 'bend', 'beneath', 'benefit', 'beside', 'besides',
  'best', 'bet', 'better', 'between', 'beyond', 'bicycle', 'bid', 'big', 'bike', 'bill', 'billion',
  'bind', 'biological', 'bird', 'birth', 'birthday', 'bit', 'bite', 'bitter', 'black', 'blade',
  'blame', 'blank', 'blanket', 'blast', 'bleed', 'blend', 'bless', 'blind', 'block', 'blood',
  'blow', 'blue', 'board', 'boat', 'body', 'boil', 'bold', 'bomb', 'bond', 'bone', 'book', 'boom',
  'boost', 'boot', 'border', 'boring', 'born', 'borrow', 'boss', 'both', 'bother', 'bottle',
  'bottom', 'boundary', 'bowl', 'box', 'boy', 'brain', 'branch', 'brand', 'brave', 'bread',
  'break', 'breakfast', 'breast', 'breath', 'breathe', 'brick', 'bridge', 'brief', 'briefly',
  'bright', 'brilliant', 'bring', 'broad', 'broken', 'brother', 'brown', 'brush', 'buck', 'budget',
  'build', 'building', 'bullet', 'bunch', 'burden', 'burn', 'bury', 'bus', 'bush', 'business',
  'busy', 'but', 'butter', 'button', 'buy', 'buyer', 'by', 'cabin', 'cabinet', 'cable', 'cake',
  'calculate', 'call', 'calm', 'camera', 'camp', 'campaign', 'campus', 'can', 'canal', 'cancel',
  'cancer', 'candidate', 'candle', 'candy', 'cannon', 'canvas', 'cap', 'capability', 'capable',
  'capacity', 'capital', 'captain', 'capture', 'car', 'carbon', 'card', 'care', 'career', 'careful',
  'carefully', 'careless', 'cargo', 'carpet', 'carry', 'cart', 'case', 'cash', 'cast', 'casual',
  'cat', 'catch', 'category', 'cattle', 'caught', 'cause', 'ceiling', 'celebrate', 'celebration',
  'celebrity', 'cell', 'cent', 'center', 'central', 'century', 'ceremony', 'certain', 'certainly',
  'chain', 'chair', 'chairman', 'challenge', 'chamber', 'champion', 'championship', 'chance',
  'change', 'changing', 'channel', 'chapter', 'character', 'characteristic', 'characterize', 'charge',
  'charity', 'chart', 'chase', 'cheap', 'check', 'cheek', 'cheer', 'cheese', 'chef', 'chemical',
  'chest', 'chicken', 'chief', 'child', 'childhood', 'chip', 'chocolate', 'choice', 'cholesterol',
  'choose', 'chose', 'chosen', 'church', 'cigarette', 'circle', 'circumstance', 'cite', 'citizen',
  'city', 'civil', 'civilian', 'claim', 'class', 'classic', 'classroom', 'clay', 'clean', 'clear',
  'clearly', 'clerk', 'click', 'client', 'cliff', 'climate', 'climb', 'clinic', 'clinical', 'clock',
  'close', 'closely', 'closer', 'cloth', 'clothes', 'clothing', 'cloud', 'club', 'clue', 'cluster',
  'coach', 'coal', 'coast', 'coat', 'code', 'coffee', 'cognitive', 'cold', 'collapse', 'colleague',
  'collect', 'collection', 'collective', 'college', 'colonial', 'colony', 'color', 'column',
  'combination', 'combine', 'come', 'comedy', 'comfort', 'comfortable', 'command', 'commander',
  'comment', 'commercial', 'commission', 'commit', 'commitment', 'committee', 'common', 'commonly',
  'communicate', 'communication', 'community', 'company', 'compare', 'comparison', 'compete',
  'competition', 'competitive', 'competitor', 'complain', 'complaint', 'complete', 'completely',
  'complex', 'complicated', 'component', 'compose', 'composition', 'comprehensive', 'computer',
  'concentrate', 'concentration', 'concept', 'concern', 'concerned', 'concert', 'conclude',
  'conclusion', 'concrete', 'condition', 'conduct', 'conference', 'confidence', 'confident',
  'confirm', 'conflict', 'confront', 'confusion', 'congressional', 'connect', 'connection',
  'consciousness', 'consensus', 'consequence', 'conservative', 'consider', 'considerable',
  'consideration', 'consist', 'consistent', 'constant', 'constantly', 'constitute', 'constitutional',
  'construct', 'construction', 'consultant', 'consume', 'consumer', 'consumption', 'contact',
  'contain', 'container', 'contemporary', 'content', 'contest', 'context', 'continue', 'continued',
  'continuous', 'contract', 'contrast', 'contribute', 'contribution', 'control', 'controversial',
  'controversy', 'convention', 'conventional', 'conversation', 'convert', 'conviction', 'convince',
  'cook', 'cookie', 'cooking', 'cool', 'cooperation', 'cope', 'copy', 'core', 'corn', 'corner',
  'corporate', 'corporation', 'correct', 'correspondent', 'cost', 'cotton', 'couch', 'could',
  'council', 'counselor', 'count', 'counter', 'country', 'county', 'couple', 'courage', 'course',
  'court', 'cousin', 'cover', 'coverage', 'cow', 'crack', 'craft', 'crash', 'crazy', 'cream',
  'create', 'creation', 'creative', 'creature', 'credit', 'crew', 'crime', 'criminal', 'crisis',
  'critic', 'critical', 'criticism', 'criticize', 'crop', 'cross', 'crowd', 'crucial', 'cry',
  'cultural', 'culture', 'cup', 'curious', 'current', 'currently', 'curriculum', 'curtain', 'curve',
  'custom', 'customer', 'cut', 'cycle', 'dad', 'daily', 'damage', 'dance', 'dancer', 'danger',
  'dangerous', 'dare', 'dark', 'darkness', 'data', 'date', 'daughter', 'dawn', 'day', 'dead',
  'deal', 'dealer', 'dear', 'death', 'debate', 'debt', 'decade', 'decide', 'decision', 'deck',
  'declare', 'decline', 'decrease', 'deep', 'deeply', 'deer', 'defeat', 'defend', 'defendant',
  'defense', 'defensive', 'deficit', 'define', 'definitely', 'definition', 'degree', 'delay',
  'deliver', 'delivery', 'demand', 'democracy', 'democratic', 'demonstrate', 'demonstration', 'deny',
  'department', 'departure', 'depend', 'dependent', 'depending', 'depict', 'depression', 'depth',
  'deputy', 'derive', 'describe', 'description', 'desert', 'deserve', 'design', 'designer',
  'desirable', 'desire', 'desk', 'desperate', 'despite', 'destroy', 'destruction', 'detail',
  'detailed', 'detect', 'determine', 'develop', 'developing', 'development', 'device', 'devote',
  'dialogue', 'die', 'diet', 'differ', 'difference', 'different', 'differently', 'difficult',
  'difficulty', 'dig', 'digital', 'dimension', 'dining', 'dinner', 'direct', 'direction',
  'directly', 'director', 'dirt', 'dirty', 'disability', 'disagree', 'disappear', 'disaster',
  'discipline', 'discourse', 'discover', 'discovery', 'discrimination', 'discuss', 'discussion',
  'disease', 'dish', 'dismiss', 'disorder', 'display', 'dispute', 'distance', 'distant', 'distinct',
  'distinction', 'distinguish', 'distribute', 'distribution', 'district', 'diverse', 'diversity',
  'divide', 'division', 'divorce', 'dna', 'do', 'doctor', 'document', 'dog', 'dollar', 'domain',
  'domestic', 'dominant', 'dominate', 'door', 'double', 'doubt', 'down', 'downtown', 'dozen',
  'draft', 'drag', 'drama', 'dramatic', 'dramatically', 'draw', 'drawing', 'dream', 'dress',
  'drink', 'drive', 'driver', 'drop', 'drug', 'dry', 'due', 'during', 'dust', 'duty', 'each',
  'eager', 'ear', 'early', 'earn', 'earth', 'ease', 'easily', 'east', 'eastern', 'easy', 'eat',
  'economic', 'economics', 'economist', 'economy', 'edge', 'edition', 'editor', 'educate',
  'education', 'educational', 'educator', 'effect', 'effective', 'effectively', 'efficiency',
  'efficient', 'effort', 'egg', 'eight', 'either', 'elderly', 'elect', 'election', 'electric',
  'electricity', 'electronic', 'element', 'elementary', 'eliminate', 'elite', 'else', 'elsewhere',
  'e-mail', 'embrace', 'emerge', 'emergency', 'emission', 'emotion', 'emotional', 'emphasis',
  'emphasize', 'employ', 'employee', 'employer', 'employment', 'empty', 'enable', 'encounter',
  'encourage', 'end', 'enemy', 'energy', 'enforcement', 'engage', 'engine', 'engineer',
  'engineering', 'English', 'enhance', 'enjoy', 'enormous', 'enough', 'ensure', 'enter', 'enterprise',
  'entertainment', 'entire', 'entirely', 'entrance', 'entry', 'environment', 'environmental',
  'episode', 'equal', 'equally', 'equation', 'equipment', 'era', 'error', 'escape', 'especially',
  'essay', 'essential', 'essentially', 'establish', 'establishment', 'estate', 'estimate', 'etc',
  'ethnic', 'European', 'evaluate', 'evaluation', 'even', 'evening', 'event', 'eventually', 'ever',
  'every', 'everybody', 'everyday', 'everyone', 'everything', 'everywhere', 'evidence', 'evident',
  'evil', 'evolution', 'evolve', 'exact', 'exactly', 'examination', 'examine', 'example', 'exceed',
  'excellent', 'except', 'exception', 'exchange', 'exciting', 'executive', 'exercise', 'exhibit',
  'exhibition', 'exist', 'existence', 'existing', 'expand', 'expansion', 'expect', 'expectation',
  'expected', 'expense', 'expensive', 'experience', 'experienced', 'experiment', 'expert', 'explain',
  'explanation', 'explicit', 'explore', 'explosion', 'expose', 'exposure', 'express', 'expression',
  'extend', 'extension', 'extensive', 'extent', 'external', 'extra', 'extraordinary', 'extreme',
  'extremely', 'eye', 'fabric', 'face', 'facility', 'fact', 'factor', 'factory', 'faculty', 'fade',
  'fail', 'failure', 'fair', 'fairly', 'faith', 'fall', 'false', 'familiar', 'family', 'famous',
  'fan', 'fancy', 'fantasy', 'far', 'farm', 'farmer', 'fashion', 'fast', 'fat', 'fate', 'father',
  'fault', 'favor', 'favorite', 'fear', 'feature', 'federal', 'fee', 'feed', 'feel', 'feeling',
  'fellow', 'female', 'fence', 'few', 'fewer', 'fiber', 'fiction', 'field', 'fifteen', 'fifth',
  'fifty', 'fight', 'fighter', 'fighting', 'figure', 'file', 'fill', 'film', 'filter', 'final',
  'finally', 'finance', 'financial', 'find', 'finding', 'fine', 'finger', 'finish', 'fire', 'firm',
  'first', 'fish', 'fishing', 'fit', 'fitness', 'five', 'fix', 'flag', 'flame', 'flat', 'flavor',
  'flee', 'flesh', 'flight', 'float', 'floor', 'flow', 'flower', 'fly', 'focus', 'folk', 'follow',
  'following', 'food', 'foot', 'football', 'for', 'force', 'foreign', 'forest', 'forever', 'forget',
  'form', 'formal', 'formation', 'former', 'formula', 'forth', 'fortune', 'forward', 'found',
  'foundation', 'founder', 'four', 'fourth', 'frame', 'framework', 'free', 'freedom', 'freeze',
  'French', 'frequency', 'frequent', 'frequently', 'fresh', 'friend', 'friendly', 'friendship',
  'frighten', 'from', 'front', 'fruit', 'frustration', 'fuel', 'full', 'fully', 'fun', 'function',
  'fund', 'fundamental', 'funding', 'funny', 'furniture', 'furthermore', 'future', 'gain', 'galaxy',
  'gallery', 'game', 'gang', 'gap', 'garage', 'garden', 'garlic', 'gas', 'gate', 'gather',
  'gauge', 'gay', 'gaze', 'gear', 'gender', 'gene', 'general', 'generally', 'generate',
  'generation', 'genetic', 'genius', 'genre', 'gentle', 'gentleman', 'gently', 'genuine', 'German',
  'gesture', 'get', 'ghost', 'giant', 'gift', 'girl', 'girlfriend', 'give', 'given', 'glad',
  'glance', 'glass', 'global', 'globe', 'glory', 'go', 'goal', 'God', 'gold', 'golf', 'good',
  'government', 'governor', 'grab', 'grade', 'gradually', 'graduate', 'grain', 'grand',
  'grandfather', 'grandmother', 'grant', 'grass', 'grave', 'gray', 'great', 'greatest', 'greatly',
  'green', 'greet', 'grin', 'grip', 'grocery', 'gross', 'ground', 'group', 'grow', 'growing',
  'growth', 'guarantee', 'guard', 'guess', 'guest', 'guide', 'guilt', 'guilty', 'gun', 'guy',
  'habit', 'habitat', 'hair', 'half', 'hall', 'hand', 'handle', 'hang', 'happen', 'happily',
  'happiness', 'happy', 'harass', 'hard', 'hardly', 'harm', 'harmful', 'harmony', 'harsh',
  'harvest', 'hat', 'hate', 'have', 'he', 'head', 'headline', 'headquarters', 'heal', 'health',
  'healthy', 'hear', 'hearing', 'heart', 'heat', 'heaven', 'heavily', 'heavy', 'heel', 'height',
  'helicopter', 'hell', 'hello', 'help', 'helpful', 'hence', 'her', 'here', 'heritage', 'hero',
  'herself', 'hey', 'hi', 'hide', 'high', 'highlight', 'highly', 'highway', 'hill', 'him',
  'himself', 'hip', 'hire', 'his', 'historian', 'historic', 'historical', 'history', 'hit',
  'hobby', 'hockey', 'hold', 'hole', 'holiday', 'holy', 'home', 'homeless', 'homework', 'honest',
  'honey', 'honor', 'hook', 'hope', 'horizon', 'horror', 'horse', 'hospital', 'host', 'hot',
  'hotel', 'hour', 'house', 'household', 'housing', 'how', 'however', 'huge', 'human', 'humor',
  'hundred', 'hungry', 'hunter', 'hunting', 'hurt', 'husband', 'hypothesis', 'I', 'ice', 'idea',
  'ideal', 'identification', 'identify', 'identity', 'ie', 'if', 'ignore', 'ill', 'illegal',
  'illness', 'illustrate', 'image', 'imagination', 'imagine', 'immediate', 'immediately', 'immigrant',
  'immigration', 'impact', 'implement', 'implication', 'imply', 'import', 'importance', 'important',
  'importantly', 'impose', 'impossible', 'impress', 'impression', 'impressive', 'improve',
  'improvement', 'in', 'incentive', 'incident', 'include', 'including', 'income', 'incorporate',
  'increase', 'increased', 'increasing', 'increasingly', 'incredible', 'indeed', 'independence',
  'independent', 'index', 'Indian', 'indicate', 'indication', 'individual', 'industrial',
  'industry', 'inevitable', 'inevitably', 'infant', 'infection', 'inflation', 'influence',
  'inform', 'informal', 'information', 'ingredient', 'initial', 'initially', 'initiative',
  'injury', 'inner', 'innocent', 'innovation', 'input', 'inquiry', 'inside', 'insight', 'insist',
  'inspire', 'install', 'instance', 'instead', 'institution', 'institutional', 'instruction',
  'instructor', 'instrument', 'insurance', 'intellectual', 'intelligence', 'intelligent',
  'intend', 'intense', 'intensity', 'intention', 'interaction', 'interest', 'interested',
  'interesting', 'internal', 'international', 'Internet', 'interpret', 'interpretation',
  'intervention', 'interview', 'into', 'introduce', 'introduction', 'invasion', 'invest',
  'investigate', 'investigation', 'investigator', 'investment', 'investor', 'invite', 'involve',
  'involved', 'involvement', 'iron', 'island', 'isolate', 'issue', 'it', 'Italian', 'item',
  'its', 'itself', 'jacket', 'jail', 'jam', 'Japanese', 'jar', 'jaw', 'jazz', 'jeans', 'jet',
  'Jew', 'Jewish', 'job', 'join', 'joint', 'joke', 'journal', 'journalist', 'journey', 'joy',
  'judge', 'judgment', 'juice', 'jump', 'junior', 'jury', 'just', 'justice', 'justify', 'keep',
  'key', 'kick', 'kid', 'kill', 'killer', 'killing', 'kind', 'king', 'kiss', 'kitchen', 'knee',
  'knife', 'knock', 'know', 'knowledge', 'lab', 'label', 'labor', 'laboratory', 'lack', 'lady',
  'lake', 'land', 'landscape', 'language', 'lap', 'large', 'largely', 'last', 'late', 'later',
  'Latin', 'latter', 'laugh', 'launch', 'law', 'lawn', 'lawsuit', 'lawyer', 'lay', 'layer',
  'lead', 'leader', 'leadership', 'leading', 'leaf', 'league', 'lean', 'learn', 'learning',
  'least', 'leather', 'leave', 'left', 'leg', 'legal', 'legend', 'legislation', 'legitimate',
  'lemon', 'length', 'less', 'lesson', 'let', 'letter', 'level', 'liberal', 'library', 'license',
  'lie', 'life', 'lifestyle', 'lifetime', 'lift', 'light', 'like', 'likely', 'limit', 'limitation',
  'limited', 'line', 'link', 'lip', 'list', 'listen', 'literally', 'literary', 'literature',
  'little', 'live', 'living', 'load', 'loan', 'lobby', 'local', 'locate', 'location', 'lock',
  'long', 'long-term', 'look', 'loose', 'lose', 'loss', 'lost', 'lot', 'lots', 'loud', 'love',
  'lovely', 'lover', 'low', 'lower', 'luck', 'lucky', 'lunch', 'lung', 'machine', 'mad', 'magazine',
  'magic', 'mail', 'main', 'mainly', 'maintain', 'maintenance', 'major', 'majority', 'make',
  'maker', 'makeup', 'male', 'mall', 'man', 'manage', 'management', 'manager', 'manner', 'manufacturer',
  'manufacturing', 'many', 'map', 'march', 'margin', 'mark', 'market', 'marketing', 'marriage',
  'married', 'marry', 'mask', 'mass', 'massive', 'master', 'match', 'mate', 'material', 'math',
  'matter', 'may', 'maybe', 'mayor', 'me', 'meal', 'mean', 'meaning', 'meanwhile', 'measure',
  'measurement', 'meat', 'mechanism', 'media', 'medical', 'medication', 'medicine', 'medium',
  'meet', 'meeting', 'member', 'membership', 'memory', 'mental', 'mention', 'menu', 'mere',
  'merely', 'mess', 'message', 'metal', 'meter', 'method', 'Mexican', 'middle', 'might', 'mile',
  'military', 'milk', 'million', 'mind', 'mine', 'minister', 'minor', 'minority', 'minute',
  'miracle', 'mirror', 'miss', 'missile', 'mission', 'mistake', 'mix', 'mixture', 'mm-hmm',
  'mode', 'model', 'moderate', 'modern', 'modest', 'mom', 'moment', 'money', 'monitor', 'month',
  'mood', 'moon', 'moral', 'more', 'moreover', 'morning', 'mortgage', 'most', 'mostly', 'mother',
  'motion', 'motivation', 'motor', 'mount', 'mountain', 'mouse', 'mouth', 'move', 'movement',
  'movie', 'Mr', 'Mrs', 'Ms', 'much', 'multiple', 'murder', 'muscle', 'museum', 'music',
  'musical', 'musician', 'must', 'mutual', 'my', 'myself', 'mystery', 'myth', 'nail', 'name',
  'narrative', 'narrow', 'nation', 'national', 'native', 'natural', 'naturally', 'nature', 'near',
  'nearby', 'nearly', 'necessarily', 'necessary', 'neck', 'need', 'negative', 'neighbor',
  'neighborhood', 'neither', 'nerve', 'nervous', 'nest', 'net', 'network', 'never', 'nevertheless',
  'new', 'newly', 'news', 'newspaper', 'next', 'nice', 'night', 'nightmare', 'nine', 'no', 'nobody',
  'nod', 'noise', 'nominate', 'none', 'nonetheless', 'noon', 'nor', 'normal', 'normally', 'north',
  'northern', 'nose', 'not', 'note', 'nothing', 'notice', 'notion', 'novel', 'now', 'nowhere',
  'nuclear', 'number', 'numerous', 'nurse', 'nut', 'object', 'objective', 'obligation', 'observe',
  'observer', 'obtain', 'obvious', 'obviously', 'occasion', 'occasionally', 'occupy', 'occur',
  'ocean', 'odd', 'odds', 'of', 'off', 'offense', 'offensive', 'offer', 'office', 'officer',
  'official', 'often', 'oh', 'oil', 'ok', 'okay', 'old', 'on', 'once', 'one', 'ongoing', 'onion',
  'online', 'only', 'onto', 'open', 'opening', 'operate', 'operating', 'operation', 'operator',
  'opinion', 'opponent', 'opportunity', 'oppose', 'opposite', 'opposition', 'option', 'or', 'orange',
  'order', 'ordinary', 'organ', 'organic', 'organization', 'organize', 'orientation', 'origin',
  'original', 'originally', 'other', 'others', 'otherwise', 'ought', 'our', 'ourselves', 'out',
  'outcome', 'outside', 'oven', 'over', 'overall', 'overcome', 'overlook', 'owe', 'own', 'owner',
  'pace', 'pack', 'package', 'page', 'pain', 'painful', 'paint', 'painter', 'painting', 'pair',
  'pale', 'pan', 'panel', 'pant', 'paper', 'parent', 'park', 'parking', 'part', 'participant',
  'participate', 'participation', 'particular', 'particularly', 'partly', 'partner', 'partnership',
  'party', 'pass', 'passage', 'passenger', 'passion', 'past', 'patch', 'path', 'patient',
  'pattern', 'pause', 'pay', 'payment', 'peace', 'peak', 'peer', 'pen', 'penalty', 'people',
  'pepper', 'per', 'perceive', 'percentage', 'perception', 'perfect', 'perfectly', 'perform',
  'performance', 'perhaps', 'period', 'permanent', 'permission', 'permit', 'person', 'personal',
  'personality', 'personally', 'personnel', 'perspective', 'persuade', 'pet', 'phase', 'phenomenon',
  'philosophy', 'phone', 'photo', 'photograph', 'photographer', 'phrase', 'physical', 'physically',
  'physician', 'piano', 'pick', 'picture', 'pie', 'piece', 'pile', 'pilot', 'pine', 'pink',
  'pipe', 'pitch', 'place', 'plan', 'plane', 'planet', 'planning', 'plant', 'plastic', 'plate',
  'platform', 'play', 'player', 'please', 'pleasure', 'plenty', 'plot', 'plus', 'PM', 'pocket',
  'poem', 'poet', 'poetry', 'point', 'pole', 'police', 'policy', 'political', 'politically',
  'politician', 'politics', 'poll', 'pollution', 'pool', 'poor', 'pop', 'popular', 'population',
  'port', 'portion', 'portrait', 'portray', 'pose', 'position', 'positive', 'possess', 'possibility',
  'possible', 'possibly', 'post', 'pot', 'potato', 'potential', 'potentially', 'pound', 'pour',
  'poverty', 'powder', 'power', 'powerful', 'practical', 'practice', 'pray', 'prayer', 'precisely',
  'predict', 'prefer', 'preference', 'pregnancy', 'pregnant', 'preparation', 'prepare',
  'presence', 'present', 'presentation', 'preserve', 'president', 'presidential', 'press',
  'pressure', 'pretend', 'pretty', 'prevent', 'previous', 'previously', 'price', 'pride',
  'priest', 'primarily', 'primary', 'prime', 'principal', 'principle', 'print', 'prior',
  'priority', 'prison', 'prisoner', 'privacy', 'private', 'probably', 'problem', 'procedure',
  'proceed', 'process', 'produce', 'producer', 'product', 'production', 'profession', 'professional',
  'professor', 'profile', 'profit', 'program', 'progress', 'project', 'prominent', 'promise',
  'promote', 'prompt', 'proof', 'proper', 'properly', 'property', 'proportion', 'proposal',
  'propose', 'proposed', 'prosecutor', 'prospect', 'protect', 'protection', 'protein', 'protest',
  'proud', 'prove', 'provide', 'provider', 'province', 'provision', 'psychiatric', 'psychological',
  'psychologist', 'psychology', 'public', 'publication', 'publicly', 'publish', 'publisher',
  'pull', 'punishment', 'purchase', 'pure', 'purpose', 'pursue', 'push', 'put', 'qualify',
  'quality', 'quarter', 'quarterback', 'question', 'quick', 'quickly', 'quiet', 'quietly', 'quit',
  'quite', 'quote', 'race', 'racial', 'radical', 'radio', 'rail', 'rain', 'raise', 'range',
  'rank', 'rapid', 'rapidly', 'rare', 'rarely', 'rate', 'rather', 'rating', 'ratio', 'raw',
  'reach', 'react', 'reaction', 'read', 'reader', 'reading', 'ready', 'real', 'reality', 'realize',
  'really', 'reason', 'reasonable', 'reasonably', 'recall', 'receive', 'recent', 'recently',
  'recipe', 'recognition', 'recognize', 'recommend', 'recommendation', 'record', 'recording',
  'recover', 'recovery', 'recruit', 'red', 'reduce', 'reduction', 'refer', 'reference', 'reflect',
  'reflection', 'reform', 'refugee', 'refuse', 'regard', 'regarding', 'regardless', 'regime',
  'region', 'regional', 'register', 'regular', 'regularly', 'regulate', 'regulation', 'regulator',
  'regulatory', 'reject', 'relate', 'relation', 'relationship', 'relative', 'relatively', 'relax',
  'release', 'relevant', 'reliability', 'reliable', 'relief', 'religion', 'religious', 'reluctant',
  'rely', 'remain', 'remaining', 'remarkable', 'remember', 'remind', 'remote', 'remove',
  'repeatedly', 'replacement', 'reply', 'report', 'reporter', 'represent', 'representation',
  'representative', 'Republican', 'reputation', 'request', 'require', 'requirement', 'rescue',
  'research', 'researcher', 'resemble', 'reservation', 'resident', 'resist', 'resistance',
  'resolution', 'resolve', 'resort', 'resource', 'respect', 'respond', 'respondent', 'response',
  'responsibility', 'responsible', 'rest', 'restaurant', 'restore', 'restriction', 'result',
  'resume', 'retail', 'retain', 'retire', 'retirement', 'return', 'reveal', 'revenue', 'review',
  'revolution', 'reward', 'rhythm', 'rice', 'rich', 'rid', 'ride', 'rifle', 'right', 'ring',
  'rise', 'risk', 'river', 'road', 'robot', 'rock', 'role', 'roll', 'romantic', 'roof', 'room',
  'root', 'rope', 'rose', 'rough', 'roughly', 'round', 'route', 'routine', 'row', 'rub', 'rule',
  'run', 'running', 'rural', 'rush', 'Russian', 'sack', 'sacred', 'sad', 'safe', 'safety', 'sail',
  'sake', 'salad', 'salary', 'sale', 'salt', 'same', 'sample', 'sanction', 'sand', 'sandwich',
  'satellite', 'satisfaction', 'satisfy', 'sauce', 'save', 'saving', 'saw', 'say', 'scale',
  'scandal', 'scared', 'scenario', 'scene', 'schedule', 'scheme', 'scholar', 'scholarship',
  'school', 'science', 'scientific', 'scientist', 'scope', 'score', 'scream', 'screen', 'script',
  'sea', 'search', 'season', 'seat', 'second', 'secret', 'secretary', 'section', 'sector',
  'secure', 'security', 'see', 'seed', 'seek', 'seem', 'segment', 'seize', 'select', 'selection',
  'self', 'sell', 'Senate', 'senator', 'send', 'senior', 'sense', 'sensitive', 'sentence',
  'separate', 'sequence', 'series', 'serious', 'seriously', 'serve', 'service', 'session', 'set',
  'setting', 'settle', 'settlement', 'seven', 'several', 'severe', 'sex', 'sexual', 'shade',
  'shadow', 'shake', 'shall', 'shape', 'share', 'sharp', 'she', 'sheet', 'shelf', 'shell',
  'shelter', 'shift', 'shine', 'ship', 'shirt', 'shit', 'shock', 'shoe', 'shoot', 'shop',
  'shopping', 'shore', 'short', 'shortly', 'shot', 'should', 'shoulder', 'shout', 'show',
  'shower', 'shrug', 'shut', 'sick', 'side', 'sigh', 'sight', 'sign', 'signal', 'significance',
  'significant', 'significantly', 'silence', 'silent', 'silly', 'silver', 'similar', 'similarly',
  'simple', 'simply', 'simultaneously', 'since', 'sing', 'singer', 'single', 'sink', 'sir',
  'sister', 'sit', 'site', 'situation', 'six', 'size', 'ski', 'skill', 'skin', 'sky', 'slave',
  'sleep', 'slice', 'slide', 'slight', 'slightly', 'slip', 'slow', 'slowly', 'small', 'smart',
  'smell', 'smile', 'smoke', 'smooth', 'snap', 'snow', 'so', 'so-called', 'soccer', 'social',
  'society', 'sock', 'soft', 'software', 'soil', 'solar', 'soldier', 'solid', 'solution', 'solve',
  'some', 'somebody', 'somehow', 'someone', 'something', 'sometimes', 'somewhat', 'somewhere',
  'son', 'song', 'soon', 'sophisticated', 'sorry', 'sort', 'soul', 'sound', 'soup', 'source',
  'south', 'southern', 'space', 'Spanish', 'speak', 'speaker', 'special', 'specialist',
  'species', 'specific', 'specifically', 'specify', 'speech', 'speed', 'spend', 'spending',
  'spin', 'spirit', 'spiritual', 'spit', 'split', 'spokesman', 'sport', 'spot', 'spread',
  'spring', 'square', 'squeeze', 'stability', 'stable', 'staff', 'stage', 'stair', 'stake',
  'stand', 'standard', 'standing', 'star', 'stare', 'start', 'state', 'statement', 'station',
  'statistics', 'status', 'stay', 'steady', 'steal', 'steel', 'step', 'stick', 'still', 'stir',
  'stock', 'stomach', 'stone', 'stop', 'storage', 'store', 'storm', 'story', 'straight',
  'strange', 'stranger', 'strategic', 'strategy', 'stream', 'street', 'strength', 'strengthen',
  'stress', 'stretch', 'strike', 'string', 'strip', 'stroke', 'strong', 'strongly', 'structure',
  'struggle', 'student', 'studio', 'study', 'stuff', 'stupid', 'style', 'subject', 'submit',
  'subsequent', 'substance', 'substantial', 'substantially', 'succeed', 'success', 'successful',
  'successfully', 'such', 'suddenly', 'suffer', 'sufficient', 'sugar', 'suggest', 'suggestion',
  'suicide', 'suit', 'suitable', 'sum', 'summary', 'summer', 'summit', 'sun', 'super', 'supply',
  'support', 'supporter', 'suppose', 'sure', 'surely', 'surface', 'surgery', 'surprise',
  'surprised', 'surprising', 'surprisingly', 'surround', 'survey', 'survival', 'survive',
  'survivor', 'suspect', 'sustain', 'swear', 'sweep', 'sweet', 'swim', 'swing', 'switch', 'symbol',
  'symptom', 'syndrome', 'system', 'table', 'tackle', 'tail', 'take', 'tale', 'talent', 'talk',
  'tall', 'tank', 'tap', 'tape', 'target', 'task', 'taste', 'tax', 'taxpayer', 'tea', 'teach',
  'teacher', 'team', 'tear', 'teaspoon', 'technical', 'technique', 'technology', 'teen',
  'teenager', 'telephone', 'tell', 'temperature', 'temple', 'temporary', 'ten', 'tend', 'tendency',
  'tennis', 'tension', 'tent', 'term', 'terms', 'terrible', 'territory', 'terror', 'terrorist',
  'test', 'testify', 'testimony', 'testing', 'text', 'than', 'thank', 'thanks', 'that', 'the',
  'theater', 'their', 'them', 'theme', 'themselves', 'then', 'theory', 'therapy', 'there',
  'therefore', 'these', 'they', 'thick', 'thin', 'thing', 'think', 'thinking', 'third', 'thirty',
  'this', 'those', 'though', 'thought', 'thousand', 'threat', 'threaten', 'three', 'throat',
  'through', 'throughout', 'throw', 'thumb', 'thus', 'ticket', 'tie', 'tight', 'time', 'tiny',
  'tip', 'tire', 'tired', 'tissue', 'title', 'to', 'tobacco', 'today', 'toe', 'together', 'tomato',
  'tomorrow', 'tone', 'tongue', 'tonight', 'too', 'tool', 'tooth', 'top', 'topic', 'toss', 'total',
  'totally', 'touch', 'tough', 'tour', 'tourist', 'tournament', 'toward', 'towards', 'tower',
  'town', 'toy', 'trace', 'track', 'trade', 'tradition', 'traditional', 'traditionally', 'traffic',
  'tragedy', 'trail', 'train', 'training', 'transfer', 'transform', 'transformation', 'transition',
  'translate', 'transportation', 'trap', 'trash', 'travel', 'treat', 'treatment', 'treaty',
  'tree', 'tremendous', 'trend', 'trial', 'tribe', 'trick', 'trip', 'troop', 'trouble', 'truck',
  'true', 'truly', 'trust', 'truth', 'try', 'tube', 'tune', 'tunnel', 'turn', 'TV', 'twelve',
  'twenty', 'twice', 'twin', 'two', 'type', 'typical', 'typically', 'ugly', 'ultimate',
  'ultimately', 'unable', 'uncle', 'under', 'undergo', 'understand', 'understanding', 'unemployed',
  'unemployment', 'unexpected', 'unfair', 'unfortunate', 'unfortunately', 'unhappy', 'uniform',
  'union', 'unique', 'unit', 'United', 'universal', 'universe', 'university', 'unknown', 'unless',
  'unlike', 'unlikely', 'until', 'unusual', 'up', 'upon', 'upper', 'upset', 'urban', 'urge',
  'us', 'use', 'used', 'useful', 'user', 'usual', 'usually', 'utility', 'utilize', 'vacation',
  'valley', 'valuable', 'value', 'variable', 'variation', 'variety', 'various', 'vast', 'vegetable',
  'vehicle', 'venture', 'version', 'versus', 'very', 'via', 'victim', 'victory', 'video', 'view',
  'viewer', 'village', 'violence', 'violent', 'virtually', 'virtue', 'virus', 'visible', 'vision',
  'visit', 'visitor', 'visual', 'vital', 'voice', 'volume', 'volunteer', 'vote', 'voter',
  'wage', 'wait', 'wake', 'walk', 'wall', 'wander', 'want', 'war', 'warm', 'warn', 'warning',
  'wash', 'waste', 'watch', 'water', 'wave', 'way', 'we', 'weak', 'wealth', 'weapon', 'wear',
  'weather', 'web', 'website', 'wedding', 'week', 'weekend', 'weekly', 'weigh', 'weight',
  'welcome', 'welfare', 'well', 'west', 'western', 'wet', 'what', 'whatever', 'wheel', 'when',
  'whenever', 'where', 'whereas', 'wherever', 'whether', 'which', 'while', 'whisper', 'white',
  'who', 'whole', 'whom', 'whose', 'why', 'wide', 'widely', 'wife', 'wild', 'will', 'willing',
  'win', 'wind', 'window', 'wine', 'wing', 'winner', 'winter', 'wipe', 'wire', 'wise', 'wish',
  'with', 'withdraw', 'within', 'without', 'witness', 'woman', 'wonder', 'wonderful', 'wood',
  'wooden', 'word', 'work', 'worker', 'working', 'workshop', 'world', 'worried', 'worry',
  'worse', 'worth', 'would', 'wound', 'wrap', 'write', 'writer', 'writing', 'wrong', 'yard',
  'yeah', 'year', 'yell', 'yellow', 'yes', 'yesterday', 'yet', 'yield', 'you', 'young', 'your',
  'yours', 'yourself', 'youth', 'zone',
])

// Combined set for quick lookup
export const ALL_COMMON_WORDS = new Set([
  ...COMMON_WORDS_TIER_1,
  ...COMMON_WORDS_TIER_2,
  ...COMMON_WORDS_TIER_3,
])

/**
 * Get word frequency tier (1-5, where 1 is most common, 5 is rare/unknown)
 */
export function getWordFrequencyTier(word: string): number {
  const normalized = word.toLowerCase()
  
  if (COMMON_WORDS_TIER_1.has(normalized)) {
    return 1 // Top 1000 - most common
  }
  if (COMMON_WORDS_TIER_2.has(normalized)) {
    return 2 // 1000-3000 - very common
  }
  if (COMMON_WORDS_TIER_3.has(normalized)) {
    return 3 // 3000-5000 - common
  }
  if (ALL_COMMON_WORDS.has(normalized)) {
    return 4 // 5000-8000 - less common (fallback for any other common words)
  }
  
  return 5 // Rare/unknown words
}
